name: Release
on:
  push:
    branches:
      - main
      - beta
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Node and npm version
        run: node -v && npm -v

      - name: Install dependencies
        run: npm ci

      - name: Generate tokens
        run: npm run build

      - name: Run Typescript checks
        run: npm run tsc

      - name: Run tests
        run: npm test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
