name: Transform tokens send from figma
on:
  repository_dispatch:
    # the post has event_type property set to 'update-tokens' in the request body
    types: update-tokens
jobs:
  build:
    name: Transform Figma design tokens for specific platforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: mkdir "tokens" directory
        run: "mkdir -p tokens"

      - name: show tokens
        run: echo '${{ toJSON(github.event.client_payload.tokens) }}'

      - name: create json from request body
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          # use the figma filename that was sent as the filename parameter
          name: ${{ github.event.client_payload.filename }}
          # use the json string that was sent as the tokens parameter
          json: ${{ github.event.client_payload.tokens }}
          dir: "tokens"

      - name: file content
        run: cat tokens/${{ github.event.client_payload.filename }}

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        run: "npm install"

      - name: Transform design tokens
        run: "npm run transform-tokens"
      
      - name: Commit message
        run: echo {{ github.event.client_payload.commitMessage }}

      - name: Create PR with proper commit message
        uses: peter-evans/create-pull-request@v4
        if: github.event.client_payload.commitMessage != ''
        with:
          commit-message: ${{github.event.client_payload.commitMessage}}
          title: "Design tokens update ${{github.event.client_payload.commitMessage}}"
          branch: tokens-update-${{ github.run_number }}

      - name: Create PR with default commit message
        uses: peter-evans/create-pull-request@v4
        if: github.event.client_payload.commitMessage == ''
        with:
          commit-message: 'Update tokens ${{ github.run_number }}'
          title: "Design tokens update ${{ github.run_number }}"
          branch: tokens-update-${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: "master"
