name: Transform tokens send from figma
on:
  repository_dispatch:
    # the post has event_type property set to 'update-tokens' in the request body
    types: update-tokens
jobs:
  build:
    name: Transform Figma design tokens for specific platforms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: mkdir "tokens" directory
        run: "mkdir -p tokens/updates"

      - name: show tokens
        run: echo '${{ toJSON(github.event.client_payload.tokens) }}'

      - name: create json from request body
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          # use the figma filename that was sent as the filename parameter
          name: colors.json
          # use the json string that was sent as the tokens parameter
          json: ${{ github.event.client_payload.tokens }}
          dir: "tokens/updates"

      - name: file contents
        run: cat tokens/updates/colors.json

      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install
        run: "npm ci"

      - name: Build
        # This command will also merge incoming tokens in tokens/updates folder into tokens/colors.json
        run: "npm run build"

      - name: Commit message
        run: echo {{ github.event.client_payload.commitMessage }}

      - name: Create PR with proper commit message
        uses: peter-evans/create-pull-request@v4
        if: github.event.client_payload.commitMessage != ''
        with:
          commit-message: ${{github.event.client_payload.commitMessage}}
          title: "feat: design tokens update"
          branch: feat/tokens-update

      - name: Create PR with default commit message
        uses: peter-evans/create-pull-request@v4
        if: github.event.client_payload.commitMessage == ''
        with:
          commit-message: "Update tokens"
          title: "feat: design tokens update"
          branch: feat/tokens-update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: "master"
