name: Validate
on:
  push:
    branches:
      - main
  # pull_request:
  # disabled pull_request because updates comes in batches in separate branches so the tests will always fail until all updates is merged

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Run Typescript checks
        run: npm run tsc

      - name: Run tests
        run: npm test
